version: '3.1'

services:

  mongo:
    container_name: docker_mongo_yams
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - "27017:27017"

    volumes: 
      - $PWD/data:/data/db

  web:
    container_name: docker_node_yams
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    volumes: 
      - /app/node_modules
      - $PWD/app:/app
    ports: 
      - "3002:3002"